### ISSUE TITLE
Pleasance et al. Pan-cancer analysis of advanced patient tumors reveals interactions between therapy and genomic landscapes. Nat Cancer, 2020.

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1099]
https://www.nature.com/articles/s43018-020-0050-6

This study contains the following data types:
- Mutations
- Copy number alterations
- Structural variants
- Gene expression
- Mutational signatures
- Survival
- Treatments
- Response to ICIs
- Any others?

To-do:
- [ ] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by rmadupuri** [comment]
**Cohort Stats:** 570 pats - profiled using whole-genome and transcriptome sequencing

**Data Availability:** 
Clinical data - Supp Table 1, 2
Mutation rates - Source Data Extended Data Fig. 2
Mutational Signatures - Source Data Extended Data Fig. 5
Germline variants - Source Data Extended Data Fig. 8

Genomic data available at: https://www.bcgsc.ca/downloads/POG570/
POG570_small_mutations.txt.gz - Complete list of somatic small mutations (SNVs and indels).
POG570_TPM_expression.txt.gz: Expression by gene in TPM
Table_S1_Demographics.xlsx - Cohort demographics
Table_S2_Treatment.xlsx - Treatment and survival data
Table_S7_Sequencing.xlsx - Sequencing parameters

Clinical and genomic data (MAF, CNA and Expression) split to multiple studies by cancer type is also available here: https://www.personalizedoncogenomics.org/cbioportal/. This studies can be downloaded & combined.

**Status:** Study can be curated from the supplemental data but I have also emailed the author (May 26, 2021) if they can share the combined dataset since it is already been transformed to portal standards.

**Comment by rmadupuri** [comment]
The study is released at https://www.cbioportal.org/study/summary?id=pog570_bcgsc_2020.
