### ISSUE TITLE
Provisional TCGA studies do not contain sequenced case lists

### ISSUE THREAD

**Issue by dionnezaal** [cBioPortal/datahub#123]
All 32 provisional TCGA studies in datahub do not contain the cases_sequenced.txt case lists. 
This case list is for example used in the expression tab when querying multiple studies.

**Comment by jjgao** [comment]
How about other data-related case list: _cna, _cnaseq?

**Comment by dionnezaal** [comment]
The 32 provisional TCGA studies in datahub contain at least: 
_all, _cna, _RNA_Seq_v2_mRNA, _methylation_hm45.

The 32 provisional TCGA studies in datahub do not contain for example: 
_sequenced, _cna_seq.

See also [cBioPortal issue #3456](https://github.com/cBioPortal/cbioportal/issues/3456) for issue  due to missing _sequenced in cBioPortal itself.

**Comment by pieterlukasse** [comment]
`_cnaseq` or `_cna_seq`?

**Comment by pieterlukasse** [comment]
This issue is solved when:
- all TCGA provisional studies have _sequenced and _cnaseq case lists (when applicable)

**Comment by sandertan** [comment]
Related to https://github.com/cBioPortal/cbioportal/issues/3378

**Comment by pieterlukasse** [comment]
@angelicaochoa we heard you were working on this. Can you confirm?

**Comment by pieterlukasse** [comment]
This is issue is still present. None of the TCGA provisional studies seem to have `_sequenced` case list. In the UI this still leads to issues:
-  in the patient view: although #3127 is now solved, the mutations and CNA tracks are not displayed if _sequenced case list is missing (at least in 1.10.1)
- in the datasets view: "sequenced" samples is reported as 0 (at least in 1.10.1)
- in the oncoprint view: the % altered can be misleading since most queries will be done on the "all" case list

**Comment by ritikakundra** [comment]
We have a tool now that can help add the _seq and _cna. I can prioritize these for today.

**Comment by dionnezaal** [comment]
Fixed by PR #164
