### ISSUE TITLE
clinical data issues

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#131]
[study view of all studies](https://www.cbioportal.org/study?id=5c6344e4e4b0f6ce58b5e508)

CANCER_TYPE #582
- [x] CANCER_TYPE and/or CANCER_TYPE_DETAILED is NA for samples in [many studies](https://www.cbioportal.org/study?id=5c634744e4b0f6ce58b5e50f)
- [x] ONCOTREE_CODE is NA in [even more studies](https://www.cbioportal.org/study?id=5c634793e4b0d20a23997545)

Sex / Gender #583
- [x] Both sex and gender are used in different studies
- [x] Only `Male` and `Female` for values
- [x] It may be useful to add sex to women's cancer (breast, ovarian, breast, anything else) and men's cancer (prostate, testicular, and penile).

SAMPLE_TYPE #584
- [x] Normalize Sample_Type: it should only be `Primary`, `Metastasis`, `Local Recurrence`
- [x] Add Sample_Type for TCGA samples. Most of TCGA samples should be `Primary`, maybe except melanoma? Please verify.

SAMPLE_CLASS #585
- [x] Normalize Sample_Class: it should only be `Tumor`, `Cell line`, and `Xenograft`.
- [x] By default it should be `Tumor`.

**Comment by ritikakundra** [comment]
@jjgao: @inodb did a search on gdac to see how many studies use xenograft and how many use pdx and majority use PDX in sample class including all CMO projects. Should we use PDX instead?

**Comment by jjgao** [comment]
@ritikakundra sure.

**Comment by yichaoS** [comment]
@ritikakundra created spreadsheet to track progress:

CANCER TYPE
https://docs.google.com/spreadsheets/d/1yrtc-Ink7Pvtxp3OfwXsWj0X4KqRghm1_2r5QZHhfUA/edit#gid=0

SAMPLE TYPE
https://docs.google.com/spreadsheets/d/1AyondwQQPRj_CpFEoIxa-CTGdfXFPwPoTSfskPGHuqM/edit#gid=0

SAMPLE CLASS
https://docs.google.com/spreadsheets/d/10yzWeYdOOappDs8iBTRXf0Z-ajyy_z5YLAtup4qcK94/edit#gid=0

**Comment by jjgao** [comment]
@yichaoS @ritikakundra great thanks. Please keep making progress and keep updating the portal.

Have you worked out a solution to update clinical data only? @yichaoS 

cc'ing @n1zea144

**Comment by yichaoS** [comment]
included in current checklist of public cleanup

**Comment by jjgao** [comment]
@yichaoS @rmadupuri @ritikakundra I reopened this issue because they still exist in the production. Did you close it because they have been fixed in data files? If so, what would be the steps to push them out? I think we should prioritize that.

I also create separate ones for different attributes. Please close them once the data is fixed in the public portal website.

**Comment by rmadupuri** [comment]
Updated [study view of all studies](https://www.cbioportal.org/study/summary?id=5efcc270e4b070725d7d26c1%2C5efcc2b0e4b030a3bfd1265d%2C5efcbfbee4b070725d7d26ac%2C5efcc0afe4b070725d7d26b4%2C5efcc1a1e4b070725d7d26ba%2C5efcc21be4b070725d7d26be)

Current status of the attributes: (cc. @ritikakundra @yichaoS @sbabyanusha )

**1. CANCER_TYPE / CANCER_TYPE_DETAILED / ONCOTREE_CODE:** Some newly added studies are missing the oncotree codes.

**Studies missing either CT/CTD/Oncotree code column**
- [ ] brca_mskcc_2019
- [ ] gbm_mayo_pdx_sarkaria_2019
- [ ] rectal_msk_2019
- [ ] prad_mcspc_mskcc_2020
- [ ] ccle_broad_2019
- [ ] egc_trap_msk_2020
- [ ] prad_mpcproject_2018
- [ ] coad_cptac_2019
- [ ] pediatric_dkfz_2017
- [ ] nsclc_mskcc_2018
- [ ] prad_su2c_2019

**Studies which have CT/CTD/Oncotree code as NA for some samples :**
- [ ] mds_mskcc_2020
- [ ] brca_metabric
- [ ] stes_tcga_pub
- [ ] ntrk_msk_2019
- [ ] pcpg_tcga_pub
- [ ] cellline_nci60
- [ ] metastatic_solid_tumors_mich_2017
- [ ] summit_2018
- [ ] mixed_pipseq_2017

**2. SEX / GENDER:** The sex attribute values have been normalized to `Male`, `Female` across all studies. 
- [ ] coad_cptac_2019: replace Gender to Sex.
- [ ] Check if Sex was added to women's cancer (breast, ovarian, breast, anything else) and men's cancer (prostate, testicular, and penile).

**3. SAMPLE_CLASS:**
- [ ] paad_qcmg_uq_2016 & prostate_dkfz_2018 : update `Tumour` to `Tumor`
- [ ] prad_msk_2019 & rectal_msk_2019 : has values Biopsy, Organoid, Resection. Normalize the values to our accepted vocabulary.

**4. SAMPLE_TYPE:**

Accepted vocabulary: `Primary, Metastasis, Local Recurrence`. Studies to be updated.
Value | Study
-- | --
Unknown | brca_mskcc_2019
Benign_Neoplasia | ccle_broad_2019
Normal | ccle_broad_2019
Recurrence/progression | gbm_mayo_pdx_sarkaria_2019
Recurrence (contralateral hemisphere) | gbm_mayo_pdx_sarkaria_2019
Unknown_Tumor | glioma_msk_2018,rectal_msk_2019
Met | nsclc_mskcc_2015
Baseline | sclc_cancercell_gardner_2017
Paired Primary Tumor | sclc_jhu
Paired Cell Line | sclc_jhu
Primary Tumor Unpaired | sclc_jhu
Cell Line | sclc_jhu

If we strictly have to use `Recurrence` instead of `Recurrent or Relapse` and similarly.

Value | Study
-- | --
Metastatic | acc_2019
Recurrent | coadread_tcga,gbm_tcga,gbm_tcga_pan_can_atlas_2018,glioma_msk_2018,hnsc_broad,lgg_tcga,lgg_ucsf_2014,lihc_tcga,luad_tcga,ov_tcga,ov_tcga_pan_can_atlas_2018,sarc_tcga,thyroid_mskcc_2016,ucec_tcga
Relapse | blca_bgi,pediatric_dkfz_2017,sclc_cancercell_gardner_2017
