### ISSUE TITLE
retire convertExpressionZscores.pl & NormalizeExpressionLevels.java

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1327]
Currently, the calculation for zscores based on diploid samples are those based on all samples is using different script as described [here](https://github.com/cBioPortal/cbioportal/blob/master/docs/Z-Score-normalization-script.md). It would be good to clean up the old code (convertExpressionZscores.pl & NormalizeExpressionLevels.java) and support diploid based z-scores in the python code.

**Comment by rmadupuri** [comment]
The `NormalizeExpressionLevels.java` is returning truncated IDs for TCGA samples https://github.com/cBioPortal/cbioportal/blob/a75a9b4109f435b166a5d36c3454324f600512ab/core/src/main/java/org/mskcc/cbio/portal/scripts/NormalizeExpressionLevels.java#L539. For example, `TCGA-06-0125-01` is truncated to `TCGA-06-0125`. The -01, -02 etc., are removed before merging the CNA and expression file to get the list of diploid sample. This logic should be removed when implementing the script in python. cc. @jjgao @cBioPortal/curation 

An example of one such case is as reported by the user: https://groups.google.com/g/cbioportal/c/bdtTDxtPqEk/m/-ijjt7DdAgAJ?pli=1. The expression file has two samples for some patients and the CNA file has only one but when the -01 and -02 is truncated both the -01, -02 RNA-seq samples get the copy number status of -01 CNA sample. This is not an issue in most cases since there's usually one sample per patient. 

The following are the IDs from gbm_tcga where the wrong mapping is observed.
| Sample ID from RNA-seq file | Mapped Sample ID from CNA file |
|--------------|--------------|
|TCGA-06-0125-02|	TCGA-06-0125-01|
|TCGA-06-0171-02|	TCGA-06-0171-01|
|TCGA-06-0210-02|	TCGA-06-0210-01|
|TCGA-06-0211-02|	TCGA-06-0211-01|
|TCGA-06-0221-02|	TCGA-06-0221-01|
|TCGA-14-0736-02|	TCGA-14-0736-01|
|TCGA-14-1402-02|	TCGA-14-1402-01|
|TCGA-19-0957-02|	TCGA-19-0957-01|
TCGA-19-1389-02|	TCGA-19-1389-01
