### ISSUE TITLE
importGenePanel.pl fails to import gene_panel due to missing gene

### ISSUE THREAD

**Issue by kronik22** [cBioPortal/datahub#1441]
The Esophageal Squamous Cell Carcinoma (UCLA, Nat Genet 2014) gene panel fails to import causing the study import to fail: 
study tar file: escc_ucla_2014.tar.gz
gene_panel: data_gene_panel_ucla_1202.txt 
db seed: seed-cbioportal_hg19_v2.7.3.sql.gz seed version. 
db schema: 2.12.8

Warnings / Errors:
-------------------
0.  Could not find gene in the database: KIAA1804; 1x
1.  Gene panel UCLA_1202 cannot be imported because one or more genes in the panel are not found in the database, or are duplicated.; 1x
Done.
Total time:  2356 ms

I have encountered this issue with 36 out of 306 studies that i have been bulk importing into our local kubernetes cbioportal deployment. 

I checked the cbioportal datahub git repository and there is a new seed db: seed-cbioportal_hg19_v2.12.8.sql.gz. Is it possible to upgrade an existing deployment with the new seed db without wiping out the old data?

**Comment by jjgao** [comment]
@yichaoS could you help look into this? Thanks.

**Comment by yichaoS** [comment]
@jjgao @kronik22 For panel `UCLA_1202`, gene `KIAA1804` is in our latest public database (and seedDB) as an alias symbol, associated with entrez ID `84451` - thus the panel should be successfully imported. Could you query your local database instance for this gene symbol exists the same way there?

**Comment by sheridancbio** [comment]
The content of the public database for cbioportal.org will not affect the attempt to import a gene panel into a local database. @yichaoS has said that all of the current gene panels are compatible with the latest seed database available from datahub (which appears to be : seed-cbioportal_hg19_v2.12.8.sql.gz). I suggest that the cleanest solution to the user's issue is to rebuild a database from the seed-cbioportal_hg19_v2.12.8.sql.gz starting point (which will then require the re-import of all studies which had been previously imported, because the rest of the database will be lost).

The second option would be to find the compatible versions (from github history) of gene panels which match the seed database that was used when building the database, and import those gene panel files ... and then afterwards, an attempt could be made to import any missing gene panels from the current versions of the gene panels, but gene panels that fail import would need to be adjusted manually to substitute (into the gene panel file) appropriate gene identifiers (which could be numeric entrez_gene_ids) for gene symbols which could not be found. That might be a general fix for a failure to import a gene symbol in a gene panel .... manually edit the file to put in the correct entrez_gene_id (integer number - perhaps located by searching public gene symbol databases such as entrez or ncbi) in place of symbols which were not found in the gene table or alias table.

**Comment by sheridancbio** [comment]
Also, I believe that there will be difficulty if you try to import the seed database mysql file into an existing database with loaded studies. Altering the gene table contents (in particular, dropping genes) may fail or leave the system in an inconsistent state because there are foreign key constraints linking the gene table column entrez_gene_id to fields in many other tables. Removing linked records from the gene table will either propagate to these other datatypes and drop associated records from them, or (if the checking of foreign key constraints is suppressed) the database may end up with events for genes which have no corresponding entry in the gene table. So I think it is not safe to import a seed database mysql file into an existing database.
