### ISSUE TITLE
Question: What is "Broad Institute GDAC TCGA Analysis Pipeline License"?

### ISSUE THREAD

**Issue by ghost** [cBioPortal/datahub#1553]
In "README.md", there is a description on the license of TCGA data:

> TCGA data are availabe under Broad Institute GDAC TCGA Analysis Pipeline License

But what is "Broad Institute GDAC TCGA Analysis Pipeline License"?  I googled it but had no helpful answer.  Is it like ODbL or much different?

Please keep this checklist for curation of a new study.

- [ ] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by f-yutmit** [comment]
@yichaoS I would appreciate if you could answer the question because you added the sentences as shown in

https://github.com/cBioPortal/datahub/commit/4869b6a712f1672fb52d1ae0f914d388d43bed4b#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
and 

https://github.com/cBioPortal/datahub/commit/b4077c165d7c510e645eaca2acec99f88aeb640b#diff-31303cad73e00b88a89a71db7212511d253acf57ad7593b3c98a0883364dabc9

**Comment by rmadupuri** [comment]
@ghost, this refers to the Broad Institute Firehose data pipeline: https://gdac.broadinstitute.org/.
