### ISSUE TITLE
Centralize gene panel files

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/datahub#413]
Gene panel files should be curated in a single location in Github and not be stored with individual studies

**Comment by jjgao** [comment]
@schultzn I assume we are trying to address the issue that the gene panel files (e.g. meta_/data_gene_panel_*.txt in [msk_impact_2017](https://github.com/cBioPortal/datahub/tree/master/public/msk_impact_2017)) may be duplicated in studies.

A few comments/questions:

- It's a good idea to store data_gene_panel_*.txt of msk-impact panels globally.
- If a panel belongs to a non-msk study we curated, is it ok to store it in the study?
- Should we support both global and study-specific gene panels?
- We can have a global location for gene panel files for the public portal on datahub, but how about the private studies?
- Study-specific gene matrix (data_gene_matrix.txt) should always be stored with individual studies

also added @ritikakundra and @yichaoS for their comments.

**Comment by jjgao** [comment]
Maybe we can do the following:

- put all gene panels in one location on datahub for public studies, e.g. `/reference_data/gene_panels/`
- add additional gene panels (or duplicate the public ones too?) in private portals under the main cbioportal data hg server `/reference_data/gene_panels/`
- when importing a study with data_gene_matrix.txt, if the gene panels used are not in the database, import them
 - public portal pipeline will look for gene_panel on datahub only
 - private portal pipeline will look for both datahub and hg server
- add code in validator to make sure when data_gene_matrix.txt exists in a study, the gene panels used are stored under `/reference_data/gene_panels/` on datahub
- I think we should continue supporting have gene_panel data within specific studies (even if we don't do that in our system) so that others can do it that way - it might be easier if they don't have many studies and each study is self-contained.

I think there is one caveat of storing gene panels globally, the downloaded study pack will no longer be self contained, but maybe it's not too big a deal comparing to the convenience we get.

**Comment by ritikakundra** [comment]
@jjgao @schultzn : Gene panels centralized here:
https://github.com/cBioPortal/datahub/tree/master/reference_data/gene_panels
