### ISSUE TITLE
wrong mutation type for some complex insertations

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#464]
I was looking at [ERBB2 mutations](http://www.cbioportal.org/beta/results/mutations?session_id=5bf495c2e4b0627334118f35) and found one mutation type was wrongly assigned.

![image](https://user-images.githubusercontent.com/840895/48808926-90c5fa00-ecf0-11e8-938f-d7998e9e118c.png)

So I did a SQL query on the public database and found out it occurred to a few studies. Note that all of them have `-` as `reference_allele`.

stable_id | chr | start_position | end_position | reference_allele | tumor_seq_allele | protein_change | mutation_type
-- | -- | -- | -- | -- | -- | -- | --
crc_msk_2018_mutations | 16 | 72831392 | 72831393 | - | TGC | Q1730delinsRK | Frame_Shift_Ins
crc_msk_2018_mutations | 12 | 49427266 | 49427267 | - | TGC | Q3741delinsRK | Frame_Shift_Ins
crc_msk_2018_mutations | 12 | 49427266 | 49427267 | - | TGC | Q3741delinsRK | Frame_Shift_Ins
crc_msk_2018_mutations | 16 | 72831386 | 72831387 | - | TGTTGTTGC | Q1732delinsRNNK | Frame_Shift_Ins
crc_msk_2018_mutations | 7 | 140453139 | 140453140 | - | GTA | T599delinsIP | Frame_Shift_Ins
crc_msk_2018_mutations | 7 | 140453139 | 140453140 | - | GTA | T599delinsIP | Frame_Shift_Ins
crc_msk_2018_mutations | 7 | 140453139 | 140453140 | - | GTA | T599delinsIP | Frame_Shift_Ins
crc_msk_2018_mutations | 8 | 38285914 | 38285915 | - | TCA | D133delinsVN | Frame_Shift_Ins
crc_msk_2018_mutations | 9 | 135771988 | 135771989 | - | GCT | S1043delinsRA | Frame_Shift_Ins
crc_msk_2018_mutations | 9 | 135771988 | 135771989 | - | GCT | S1043delinsRA | Frame_Shift_Ins
crc_msk_2018_mutations | 17 | 37627307 | 37627308 | - | TGC | A408delinsVP | Frame_Shift_Ins
crc_msk_2018_mutations | 13 | 110438317 | 110438318 | - | GTT | N28delinsKT | Frame_Shift_Ins
crc_msk_2018_mutations | 13 | 110438317 | 110438318 | - | GTT | N28delinsKT | Frame_Shift_Ins
crc_msk_2018_mutations | 22 | 21272367 | 21272368 | - | GTGCTA | V49delinsGAM | Frame_Shift_Ins
lgg_ucsf_2014_mutations | 14 | 33242972 | 33242973 | - | GCA | C1154delinsWH | Frame_Shift_Ins
lgg_ucsf_2014_mutations | 12 | 7045938 | 7045939 | - | AGCAGCAGC | H503delinsQAAA | Frame_Shift_Ins
lgg_ucsf_2014_mutations | 17 | 39346626 | 39346627 | - | GTGGGTCCAGCTGCTGCCAGCCTTGCT | C163delinsWWVQLLPALL | Frame_Shift_Ins
lgg_ucsf_2014_mutations | 17 | 44249468 | 44249469 | - | TGA | E14delinsDQ | Frame_Shift_Ins
lgg_ucsf_2014_mutations | 17 | 44249468 | 44249469 | - | TGA | E14delinsDQ | Frame_Shift_Ins
cellline_ccle_broad_mutations | 17 | 35454852 | 35454853 | - | GTTCTT | F2211delinsLRT | Frame_Shift_Ins
cellline_ccle_broad_mutations | 17 | 37880997 | 37880998 | - | TGT | G776delinsVC | Frame_Shift_Ins
msk_impact_2017_mutations | 17 | 37880997 | 37880998 | - | TGT | G776delinsVC | Frame_Shift_Ins
cellline_ccle_broad_mutations | 3 | 40503529 | 40503530 | - | GTA | A152delinsGT | Frame_Shift_Ins
cellline_ccle_broad_mutations | 5 | 37014818 | 37014819 | - | ATA | E1532delinsDK | Frame_Shift_Ins
ampca_bcm_2016_mutations | 4 | 9784947 | 9784948 | - | AGA | G432delinsES | Frame_Shift_Ins
cellline_nci60_mutations | 10 | 102587329 | 102587330 | - | CCG | R403delinsPG | Frame_Shift_Ins
cellline_nci60_mutations | 15 | 29997760 | 29997761 | - | GGC | S1680delinsRP | Frame_Shift_Ins
cellline_nci60_mutations | 17 | 18874688 | 18874689 | - | GGA | D819delinsVH | Frame_Shift_Ins
cellline_nci60_mutations | 11 | 72145489 | 72145490 | - | AAA | K10delinsNL | Frame_Shift_Ins
cellline_nci60_mutations | 5 | 139931628 | 139931629 | - | GTT | V110delinsEL | Frame_Shift_Ins
cellline_nci60_mutations | 12 | 109017677 | 109017678 | - | CCA | P136delinsLA | Frame_Shift_Ins
cellline_nci60_mutations | 22 | 41573575 | 41573576 | - | TTG | H1954delinsLD | Frame_Shift_Ins
cellline_nci60_mutations | 17 | 15343530 | 15343531 | - | CTG | K8delinsTE | Frame_Shift_Ins
breast_msk_2018_mutations | 8 | 55372259 | 55372260 | - | CACCAG | H317delinsPPD | Frame_Shift_Ins
breast_msk_2018_mutations | 8 | 38285914 | 38285915 | - | TCA | D166delinsVN | Frame_Shift_Ins
breast_msk_2018_mutations | 14 | 38061269 | 38061270 | - | CTTGCCCGG | K240delinsNRAR | Frame_Shift_Ins
msk_impact_2017_mutations | 17 | 37880997 | 37880998 | - | CTGTGGGCT | G776delinsAVGC | Frame_Shift_Ins
msk_impact_2017_mutations | 7 | 55249013 | 55249014 | - | GCACCC | N771delinsSTH | Frame_Shift_Ins
msk_impact_2017_mutations | 16 | 68842414 | 68842415 | - | ATA | P159delinsHT | Frame_Shift_Ins
msk_impact_2017_mutations | 2 | 25463300 | 25463301 | - | TTT | F731delinsLN | Frame_Shift_Ins
msk_impact_2017_mutations | 4 | 55593607 | 55593608 | - | TCC | K558delinsNP | Frame_Shift_Ins
msk_impact_2017_mutations | 4 | 55593607 | 55593608 | - | TCC | K558delinsNP | Frame_Shift_Ins
msk_impact_2017_mutations | 17 | 7578469 | 7578470 | - | GGG | G154delinsAR | Frame_Shift_Ins
msk_impact_2017_mutations | 7 | 55249010 | 55249011 | - | GCACAC | D770delinsGTH | Frame_Shift_Ins
msk_impact_2017_mutations | 17 | 7579358 | 7579359 | - | TTT | R110delinsQS | Frame_Shift_Ins

SQL I used:
```sql
select gp.stable_id, me.chr, me.start_position, me.end_position, me.reference_allele, me.tumor_seq_allele, me.protein_change, me.mutation_type
from mutation_event me, mutation m, genetic_profile gp
where me.mutation_event_id=m.mutation_event_id and m.genetic_profile_id=gp.genetic_profile_id
and me.protein_change like "%delins%" and me.protein_change not like "%delins%*%" and me.protein_change not like "*%delins%"
and mutation_type!="Splice_Region"
and (variant_type = "INS" and mutation_type!="In_Frame_Ins" and (REFERENCE_ALLELE="-" OR REFERENCE_ALLELE="NA") AND (LENGTH(TUMOR_SEQ_ALLELE)) % 3 = 0);
```

@ritikakundra: please also run the sql in private databases and fix the data.

**Comment by yichaoS** [comment]
@jjgao @ritikakundra It is all cleared/fixed in public DB. Ran the query in private DB just now and the results are as below: (the number is # of mutations w/ this issue)

29	accrf_merged_unfiltered_mutations
29	acyc_fmi_morris_unfiltered_mutations
64	all_phase2_target_2017_mutations
315	aml_target_2017_mutations
1	blca_cmo_solitd_5931_b_mutations
1	brca_mskcc_solitd_5065_g_mutations
1	brca_sanger_2012_mutations
1	brca_sanger_2016_mutations
3	breast_msk_2017_mutations
1	cellline_cclp_sanger_mutations
20	cgci_blgsp_2017_mutations
2	coadread_cbe_saltzl_5281_mi_mutations
2	coadread_saltzl_2015_mutations
22	egc_msk_janjigy_2017_mutations
101	gbm_yale_mutations
1	gct_tcga_freeze_mutations
1	lcll_13-079_mskcc_foundation_mutations
1	lihc_tcga_pub_mutations
3	lms_cbe_agaramn_4786_mutations
1	lymphoma_filtered_merged_mutations
1	lymphoma_merged_mutations
4	mbl_icgc_2014_mutations
14	mixed_13-060_mskcc_foundation_mutations
1	mixed_13-158_mskcc_foundation_mutations
3	mixed_dmp_MSK-IMPACT_2013_mutations
22	mixed_gray_proj_06208_mutations
1	mixed_lymphoma-sa_therp_filtered_mskcc_foundation_mutations
1	mixed_lymphoma-sa_therp_mskcc_foundation_mutations
30	mixed_lymph_mskcc_foundation_160830_mutations
2	mpn_cbe_rampalr_RR_mpnaml_mutations
64	mpn_mskcc_2015_mutations
2	nbl_target_2017_mutations
1	nsclc_msk_subset_2018_mutations
2	os_target_2017_mutations
1	ovt_levine_2015_mutations
2	prad_mskcc_foundation_mutations
2	prad_su2c_2018_prad_su2c_mutations
3	thca_mskcc_faginj_2014_mutations
3	thhc_mskcc_2015_chant_mutations
1	ulm_cbe_weigeltb_BW_lmbn_mutations
1	wt_target_2017_mutations

**Comment by sbabyanusha** [comment]
This issue is fixed.
