### ISSUE TITLE
Copy-number evens missing in blca_mskcc_solit_2012

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/datahub#624]
The manuscript describes many deletions and amplifications in cancer genes, but they all seem to be missing from the study. The CNA table shows only microarrays.

https://www.cbioportal.org/study?id=blca_mskcc_solit_2012&tab=summary

![image](https://user-images.githubusercontent.com/11892704/53274950-39587100-36c7-11e9-87e7-7f6a6f87ab79.png)

**Comment by yichaoS** [comment]
@schultzn @jjgao We never had hugo symbol and sample ID in CNA data for this study, except the microRNAs (that's why only the miRNA rows got imported). 

![screen shot 2019-03-05 at 11 17 00 am](https://user-images.githubusercontent.com/5973438/53820377-a676cc80-3f39-11e9-9ec8-dfe2165970a8.png)


We temporarily removed the entire CNA file (logged here: https://github.com/cBioPortal/datahub/issues/311) and updated it in MSK portal (https://cbioportal.mskcc.org/study?id=blca_mskcc_solit_2012). Will update the public portal today (@ritikakundra @rmadupuri)
