### ISSUE TITLE
ccle study tweaks

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#846]
- change id from `mixed_broad_ccle_2018` to `ccle_broad_2019`
- pmid: 31068700
- title: Cancer Cell Line Encyclopedia (Broad, 2019)
- description: Cancer Cell Line Encyclopedia from the Broad Institute and Novartis, updated 201~~8~~9 ~~data set containing 1648 samples~~. Data downloaded from the [Broad CCLE Portal](https://portals.broadinstitute.org/ccle).

**Comment by ritikakundra** [comment]
@jjgao for the description: I updated it based on this #816

**Comment by jjgao** [comment]
Thanks, @ritikakundra, but I don't think we should mention the number of samples. Currently it is not the same as we see on the study view page, which is confusing. If we correct it, then it's redundant. Also it should be 2019. @schultzn

**Comment by yichaoS** [comment]
Study renamed and reimported to triage: https://triage.cbioportal.mskcc.org/study/summary?id=ccle_broad_2019

**Comment by paulcwvandijk** [comment]
@ritikakundra 
I've tried to upload this study to my local deploy but receive this error:
<ERROR: data_RNA_Seq_mRNA_median_Zscores.txt: lines [7884, 33912, 38209, (4 more)]: Hugo Symbol is not in gene or alias table and starts with a number. This can be caused by unintentional gene conversion in Excel.; value encountered: '5S_RRNA'>

Perhaps some edits have been made before these data have been uploaded to the public portal (deleted, changed?).
